import type { Prisma } from '@prisma/client';

/** Called inside the order transaction: retries cannot create duplicate stops.
 * Arrival order is provisional until the driver supplies their current GPS.
 * Never changes a round that has already left for delivery.
 */
export async function addToAutomaticRound(tx: Prisma.TransactionClient, orderId: string) {
  const order = await tx.order.findUniqueOrThrow({where:{id:orderId},include:{customer:true,address:true}});
  if(order.status !== 'CONFIRMED' || order.address.latitude == null || order.address.longitude == null) return;
  await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtext(${`routes:${order.deliveryDate.toISOString()}`}))`;
  if(await tx.routeStop.findFirst({where:{orderId,route:{status:{in:['PLANNED','IN_PROGRESS']}}}})) return;
  const rounds = await tx.route.findMany({where:{date:order.deliveryDate,status:'PLANNED',autoGenerated:true,awaitingDriverLocation:true},include:{_count:{select:{stops:true}}},orderBy:{createdAt:'asc'}});
  let round = rounds.find(r=>r._count.stops<25);
  if(!round) {
    const created = await tx.route.create({data:{date:order.deliveryDate,startLocationLat:order.address.latitude,startLocationLng:order.address.longitude,returnToStart:false,autoGenerated:true,awaitingDriverLocation:true}});
    round = {...created,_count:{stops:0}};
  }
  await tx.routeStop.create({data:{routeId:round.id,orderId,stopNumber:round._count.stops+1,customerNameSnapshot:order.customer.name,addressTextSnapshot:order.address.formattedAddress,latitudeSnapshot:order.address.latitude,longitudeSnapshot:order.address.longitude,quantitySnapshot:`${order.quantity}× ${order.milkSize==='ML500'?'500 ml':order.milkSize==='L1'?'1 L':`${order.customQuantityLiters} L`}`}});
  // Version check for concurrent driver optimization.
  await tx.route.update({where:{id:round.id},data:{updatedAt:new Date()}});
}
