import { db } from "@/lib/db";
import { businessDateOnlyToDate } from "@/lib/tz";
import Link from "next/link";
import { PageHeader } from "@/components/layout/PageHeader";
import { Card, CardContent } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";
import { RouteOptimizerPanel, type RoutableOrder } from "@/components/routes/RouteOptimizerPanel";
import { listRoutableOrdersForDate } from "@/lib/services/routes";
import { getDefaultStartLocation } from "@/lib/services/settings";
import { todayBusinessDateString } from "@/lib/tz";
import { MILK_SIZE_LABEL } from "@/lib/statusStyles";

export default async function RoutesPage({
  searchParams,
}: {
  searchParams: Promise<{ orderIds?: string; date?: string }>;
}) {
  const { orderIds, date } = await searchParams;
  const today = date && /^\d{4}-\d{2}-\d{2}$/.test(date) && Number.isFinite(Date.parse(date)) && new Date(date).toISOString().slice(0,10)===date ? date : todayBusinessDateString();

  const [activeRoutes, routableOrders, defaultStart] = await Promise.all([
    db.route.findMany({where:{date:businessDateOnlyToDate(today),status:{in:["PLANNED","IN_PROGRESS"]}},include:{stops:true},orderBy:{createdAt:"asc"}}),
    listRoutableOrdersForDate(today),
    getDefaultStartLocation(),
  ]);

  const orders: RoutableOrder[] = routableOrders.map((o) => ({
    id: o.id,
    customerName: o.customer.name,
    area: o.address.area,
    quantity: `${o.quantity}× ${MILK_SIZE_LABEL[o.milkSize] ?? o.milkSize}`,
  }));

  const preselectedIds = (orderIds ?? "").split(",").filter(Boolean);

  return (
    <div>
      <PageHeader title="Routes" description="Optimize and review the driver's delivery route." />

      <form className="mb-5 flex flex-wrap items-end gap-3"><label className="text-sm">Delivery date<input aria-label="Delivery date" type="date" name="date" defaultValue={today} required className="mt-1 block min-h-11 rounded-lg border border-border bg-surface px-3"/></label><button className="min-h-11 rounded-lg bg-primary px-5 text-white">Show routes</button></form>
      <p className="mb-5 text-sm text-ink-muted">Confirmed WhatsApp orders automatically form delivery rounds of up to 25 stops for their delivery date. Open a round and use driver GPS to optimize the stop order before departure.</p>
      {activeRoutes.map(activeRoute => (
        <Link key={activeRoute.id} href={`/routes/${activeRoute.id}`}>
          <Card className="mb-6 hover:border-primary/40">
            <CardContent className="flex flex-wrap items-center justify-between gap-3">
              <div>
                <p className="font-medium text-ink">
                  {activeRoute.autoGenerated ? "WhatsApp delivery round" : "Delivery round"} · {activeRoute.status === "IN_PROGRESS" ? "in progress" : "planned"}
                </p>
                <p className="text-sm text-ink-muted">
                  {activeRoute.stops.length} stops · {activeRoute.awaitingDriverLocation ? "Ready for driver GPS" : `${activeRoute.plannedDistanceKm?.toFixed(1)} km · ${activeRoute.plannedDurationMinutes} min`}
                </p>
              </div>
              <Badge tone={activeRoute.status === "IN_PROGRESS" ? "transit" : "confirmed"}>
                {activeRoute.status === "IN_PROGRESS" ? "In progress" : "Planned"}
              </Badge>
            </CardContent>
          </Card>
        </Link>
      ))}

      <p className="mb-3 text-sm font-medium text-ink">
        {activeRoutes.length ? "Plan another route" : "Plan a delivery route"}
      </p>
      <RouteOptimizerPanel
        orders={orders}
        preselectedIds={preselectedIds}
        defaultStart={{ lat: defaultStart.latitude, lng: defaultStart.longitude, label: defaultStart.label }}
      />
    </div>
  );
}
